### PR TITLE
Added mp_forms support

### PR DESCRIPTION
**Pull request by Toflar**
@leycommediasolutions is kindly sponsoring the work on this feature which allowed me to look into it. Thank you!

### CODE REVIEW

**Comment by Toflar** [comment]
You can start testing this feature by requiring `dev-feature/mp_forms-support`. Thanks for the feedback!

**Comment by Cleanerrr** [comment]
> You can start testing this feature by requiring `dev-feature/mp_forms-support`. Thanks for the feedback!

Hi,
I have only one question.
When this feature can be used? I think, when the Plugin will be updated with this feature?
Thank you very much

**Comment by Toflar** [comment]
Just released 2.3.0 :)

**Comment by Cleanerrr** [comment]
> Just released 2.3.0 :)

Than you very much :)

**Pull request merged**
